// Do not edit this file, it's used by libsdl2gui. @see "../test/MainActivity.java"

package com.libsdl2gui.lib;

import android.content.ContentResolver;
import android.content.res.Configuration;
import android.provider.Settings;

import org.libsdl.app.SDLActivity;

public class Sdl2GuiActivity extends SDLActivity
{
	public static boolean IsAutoRotate()
	{
		ContentResolver contentResolver = mSingleton.getContentResolver();
		String          rotationSetting = Settings.System.ACCELEROMETER_ROTATION;
		int             rotationValue   = Settings.System.getInt(contentResolver, rotationSetting, 0);

		return (rotationValue == 1);
	}

	public static boolean IsDarkMode()
	{
		Configuration config    = mSingleton.getResources().getConfiguration();
		int           nightMask = (config.uiMode & Configuration.UI_MODE_NIGHT_MASK);

		return (nightMask == Configuration.UI_MODE_NIGHT_YES);
	}
}
