// Do not edit this file, it's used by libsdl2gui. @see "../test/MainActivity.java"

package com.libsdl2gui.lib;

import android.content.ContentResolver;
import android.content.Context;
import android.content.res.Configuration;
import android.provider.Settings;
import android.util.DisplayMetrics;
import android.view.WindowManager;

import org.libsdl.app.SDLActivity;

public class Sdl2GuiActivity extends SDLActivity
{
	public static int GetDPI()
	{
		DisplayMetrics displayMetrics = new DisplayMetrics();
		WindowManager  windowManager  = (WindowManager)mSingleton.getSystemService(Context.WINDOW_SERVICE);

		windowManager.getDefaultDisplay().getMetrics(displayMetrics);

		return displayMetrics.densityDpi;
	}

	public static boolean IsAutoRotate()
	{
		ContentResolver contentResolver = mSingleton.getContentResolver();
		String          rotationSetting = Settings.System.ACCELEROMETER_ROTATION;
		int             rotationValue   = Settings.System.getInt(contentResolver, rotationSetting, 0);

		return (rotationValue == 1);
	}

	public static boolean IsDarkMode()
	{
		Configuration config    = mSingleton.getResources().getConfiguration();
		int           nightMask = (config.uiMode & Configuration.UI_MODE_NIGHT_MASK);

		return (nightMask == Configuration.UI_MODE_NIGHT_YES);
	}
}
